print("My name is Asna Fatima")
print("I study at Bathspa University")
print("I am doing bachelors of science in Creative Computing")
print("My age is 17")
print("My Birthday is on 3rd October 2006")
print("I live in sharjah")
print("I have a younger sister")
print("I love designin")
print("I also love travelling and exploring")
print("I really enjoy socializing")
print("I grduated from highschool in 2024")
print("I graduated from Sharjah Indian School")
print("My University is in Ras Al Khaimah")
print("I am the Class Representative")
print("I enjoy volunteering")